export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const LOGOUT_USER = 'LOGOUT_USER'

export const UPLOAD_IMAGE="UPLOAD_IMAGE"

export const HANDLE_CHANGE="HANDLE_CHANGE"


export const CHANGE_PAGE="CHANGE_PAGE"

export const GET_ALL_USERS="GET_ALL_USERS"

export const UPDATE_USER_BEGIN="UPDATE_USER_BEGIN"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR="UPDATE_USER_ERROR"

export const UPDATE_PASSWORD_BEGIN="UPDATE_PASSWORD_BEGIN"
export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_ERROR="UPDATE_PASSWORD_ERROR"

export const GET_ALL_PRODUCTS_BEGIN="GET_ALL_PRODUCTS_BEGIN"
export const GET_ALL_PRODUCTS_SUCCESS="GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_ERROR="GET_ALL_PRODUCTS_ERROR"

export const CLEAR_UPLOADS="CLEAR_UPLOADS"


export const CREATE_PRODUCT_BEGIN="SUBMIT_CREATE_PRODUCT_BEGIN"
export const  CREATE_PRODUCT_SUCCESS="SUBMIT_CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_ERROR="SUBMIT_CREATE_PRODUCT_ERROR"

export const HANDLE_UPDATE_PRODUCT="HANDLE_UPDATE_PRODUCT"

export const PRODUCT_DETAIL_ID="PRODUCT_DETAIL_ID"

export const CLEAR_REVIEW="CLEAR_REVIEW"

export const FINAL_UPDATE_PRODUCT_BEGIN="FINAL_UPDATE_PRODUCT_BEGIN"
export const FINAL_UPDATE_PRODUCT_SUCCESS="FINAL_UPDATE_PRODUCT_SUCCESS"
export const FINAL_UPDATE_PRODUCT_ERROR="FINAL_UPDATE_PRODUCT_ERROR"

export const SUBMIT_REVIEW_BEGIN="SUBMIT_REVIEW_BEGIN"
export const SUBMIT_REVIEW_SUCCESS="SUBMIT_REVIEW_SUCCESS"
export const SUBMIT_REVIEW_ERROR="SUBMIT_REVIEW_ERROR"

export const SINGLE_PERSON_REVIEW="SINGLE_PERSON_REVIEW"
export const DELETE_REVIEW="DELETE_REVIEW"


export const UPDATE_REVIEW_BEGIN="UPDATE_REVIEW_BEGIN"
export const UPDATE_REVIEW_SUCCESS="UPDATE_REVIEW_SUCCESS"
export const UPDATE_REVIEW_ERROR="UPDATE_REVIEW_ERROR"

export const GET_ADMIN_ALL_REVIEWS="GET_ADMIN_ALL_REVIEWS"

export const SINGLE_PRODUCTS_REVIEWS="SINGLE_PRODUCT_REVIEWS"


export const CREATE_ORDER_BEGIN="CREATE_ORDER_BEGIN"
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_ERROR="CREATE_ORDER_ERROR"


export const SINGLE_USER_ORDERS="SINGLE_USERS_ORDERS"
export const ADMIN_ALL_ORDERS="ADMIN_ALL_ORDERS"

export const DELETE_ORDER="DELETE_ORDER"

export const GET_STRIPE="GET_STRIPE"

export const SUCCESS_OR_FAILURE_ACTIONS="SUCCESS_OR_FAILURE_ACTIONS"

export const HANDLE_RATING="HANDLE_RATING"
